### ISSUE TITLE
  ٍError "This model's maximum context length is 4097 tokens" on COMMAND = get_hyperlinks 

### ISSUE THREAD

**Issue by hdmbn** [Significant-Gravitas/AutoGPT#4733]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Whenever AutoGPT reaches a point that requires extracting links from a website and passing them to the next command, it results in errors like "openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4192 tokens. Please reduce the length of the messages."
It seems the related command get_hyperlinks has some bug in chunking.

**Comment by Tarolrr** [comment]
Please add full error and activity logs (maintainters do need them to solve issue, see #4696). Till then, I think it needs 'need info' label (@Pwuts). Possibly, also duplicate.
Also this could be already fixed by #4652 (judging by date of the issue, this was encountered on v.0.4.0, but the mentioned PR was released on v0.4.1)
