### ISSUE TITLE
Support Agent Protocol

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#5178]
Reference: https://agentprotocol.ai/protocol

## Dependencies
- [x] #4105
- [ ] New app wrapper with FastAPI

## TODO
- [ ] Expand this TODO list

**Comment by eamonnmoloney** [comment]
Hey. Do you see this acting as a server to enable reactive processing by agents?

For example, upon receiving a mail ( an agent can either get a notification or polls for mail) an agent processes the mail and reacts. It could prompt the Human for an action, respond automatically, etc.

So, rather than a chat interface where the human asks the agent a question.... instead the agent has an interface to the human

All sources of events can drive this agents behaviour
