### ISSUE TITLE
access error

### ISSUE THREAD

**Issue by rttmoa** [Significant-Gravitas/AutoGPT#6230]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

You do not have an account because it has been deleted or deactivated. If you believe this was an error, please contact us through our help center at help.openai.com.

**Comment by Bentlybro** [comment]
"You do not have an account because it has been deleted or deactivated. If you believe this was an error, please contact us through our help center at help.openai.com." thats nothing to do with us you need to contact openai like it says to do so because from that message looks like the account was deleted or deactivated for some reason

**Comment by rttmoa** [comment]
Okay, well, after looking into it, I think it's a blocked account. Thank you. I'll figure it out. Thank you.

**Comment by leiho13** [comment]
its a blocked account

**Comment by rttmoa** [comment]
Okay, the problem has been found, thank you

**Comment by Bentlybro** [comment]
if this has been solved we can go ahead and close this
