### ISSUE TITLE
Poetry command not found 

### ISSUE THREAD

**Issue by peterZyf112358** [Significant-Gravitas/AutoGPT#6920]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I have followed the instructions and used the wsl, I did the dos2unix on run, setup, and run_benchmark. The problem seems like the poetry cannot being found 
⌛ Running setup for agent 'HOWBUY_GPT'...
./setup: line 3: poetry: command not found
No poetry environment found.
./setup: line 11: poetry: command not found
Setup completed successfully.     

⌛ (Re)starting benchmark server...
./run_benchmark: line 9: poetry: command not found

### Upload Activity Log Content

![erro_page_1](https://github.com/Significant-Gravitas/AutoGPT/assets/79706376/ce18cd43-52b2-4195-9765-03db16aef2a4)

![erro_page_2](https://github.com/Significant-Gravitas/AutoGPT/assets/79706376/342f71fe-2903-447f-9075-094fff2fb9ad)

**Comment by witheunjin** [comment]
Same issue on me, too. 
I guess you closed this issue because you solved it. 
If yes, could you share how did you solve this?

**Comment by peterZyf112358** [comment]
try not to run it on the Windows system, it causes a lot of problems. Follow the steps of the Windows system tuition.
https://github.com/Significant-Gravitas/AutoGPT/blob/master/QUICKSTART.md
You have to use dos2unix and wsl. 
(better run it on linux)

**Comment by witheunjin** [comment]
Thanks for your fast response! So nice of you :)
Actually... I've tried this on macOS, but I still faced this issue. 

HOWEVER! The following steps worked for me. 
(I hope this comment to be helpful to others)

Before I solve this issue, I face these results when I executed each command. 
1. `./run setup`
The reason of this issue is because of 'poetry'. 
(See `poetry could not be found` message in the below figure)
<img width="580" alt="image" src="https://github.com/Significant-Gravitas/AutoGPT/assets/50702052/795a32c0-999e-49ce-837c-ffd79db79c43">
2. `poetry`
Check whether `poetry' command works successfully or not by running only poetry. 
(You can see 'poetry' command is not found in the figure below)
<img width="338" alt="Screen Shot 2024-03-21 at 5 35 54 PM" src="https://github.com/Significant-Gravitas/AutoGPT/assets/50702052/0f8f7060-d0e9-408a-86a1-153f3d6b9cc2">

So, with this reference(https://www.reddit.com/r/learnpython/comments/12q7gzx/deleted_by_user/) I re-installed poetry and assured 'AutoGPT/docs/requirements.txt' to be executed successfully. 
1. Reinstall `poetry`
Command: `sudo pip3 install poetry`
2. Meet requirements of AutoGPT on `./docs/` directory
Command: `python3 -m pip install -r requirements.txt`

Then, when I execute `./run setup` command I got this. (without 'poetry command not found' message anymore)
<img width="490" alt="Screen Shot 2024-03-21 at 5 44 06 PM" src="https://github.com/Significant-Gravitas/AutoGPT/assets/50702052/1b430f11-a189-48ca-a9a3-438400f405fa">

Finally, everything works perfectly! Yeah~~ 
<img width="603" alt="Screen Shot 2024-03-21 at 5 46 16 PM" src="https://github.com/Significant-Gravitas/AutoGPT/assets/50702052/9b1440a5-c945-480b-8707-9d174ffc5e63">

Thanks to nice and kind @peterZyf112358, too 👍

**Comment by akasharunabharathi** [comment]
Hi! I tried this approach – reinstalled `poetry`, verified that AutoGPT requirements were met by running `python3 -m pip install -r ./docs/requirements.txt`, and yet, when I run `./run setup`, I still get the `poetry could not be found` message from your first screenshot. 

<img width="872" alt="Screen Shot 2024-04-04 at 3 50 04 PM" src="https://github.com/Significant-Gravitas/AutoGPT/assets/90937878/a6a0da11-e06b-4700-8c50-5ba419e832b2">

Do you have any ideas on how I can resolve this? Thanks in advance!

**Comment by akasharunabharathi** [comment]
Hi! I tried this approach – reinstalled `poetry`, verified that AutoGPT requirements were met by running `python3 -m pip install -r ./docs/requirements.txt`, and yet, when I run `./run setup`, I still get the `poetry could not be found` message from your first screenshot. 

<img width="872" alt="Screen Shot 2024-04-04 at 3 52 40 PM" src="https://github.com/Significant-Gravitas/AutoGPT/assets/90937878/32dc5bf4-634f-44fc-984a-c40be67e2132">

Do you have any ideas on how I can resolve this? Thanks in advance!

**Comment by Kunlun-Zhu** [comment]
same problem here

**Comment by MorenoLabs** [comment]
tried all variations with venv, no venv. same issue. cant uninstall poetry either... 
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/64956214/32e9176a-e68f-4b6e-8c0e-cf81333f4966)

**Comment by DaveLomber** [comment]
same here

```
(venv) AutoGPT % ./run agent start Igor2          
⌛ Running setup for agent 'Igor2'...
Path /Users/devio/workspace/AutoGPT/agents/benchmark for agbenchmark does not exist
Removed the poetry environment at /Users/devio/workspace/AutoGPT/path/to/venv.
./setup: line 11: poetry: command not found
Setup completed successfully.

⌛ (Re)starting agent 'Igor2'...
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
./run: line 9: poetry: command not found

```

**Comment by benjisho** [comment]
This fixes the error on a Linux:

```shell
mv /usr/lib/python3.12/EXTERNALLY-MANAGED /root/
pip install poetry
```
