### ISSUE TITLE
cant setup

### ISSUE THREAD

**Issue by kittenvr** [Significant-Gravitas/AutoGPT#7157]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/103120356/4a709b1a-f1d2-4580-a6f6-4d36725ad3f2)
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/103120356/b9dc2896-7521-4e84-9673-fd6c90c9d66e)

### Upload Activity Log Content

/

### Upload Error Log Content

/

**Comment by kittenvr** [comment]
i figured out to use dos2unix but other error
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/103120356/83cbe388-18b1-461b-bbce-ad3b7e070e2d)

**Comment by gws0920** [comment]
me too~ need help

**Comment by rakeshbitsindri** [comment]
i had used the initial version of autogpt when it was released, since then guys made it almost impossible to setup it on both windows and mac. :P i am tired of it just giving up. 



.venv) rakumar7@L4W31Q34M2 autogpt % cd AutoGPT 
(.venv) rakumar7@L4W31Q34M2 AutoGPT % poetry run python cli.py agent list 
Creating virtualenv autogpt-Y2PYc-k_-py3.12 in /Users/rakumar7/Library/Caches/pypoetry/virtualenvs
Collecting click
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Installing collected packages: click
Successfully installed click-8.1.7
Available agents: 🤖
        🐙 benchmark
        🐙 newbot
        🐙 bugbounty
        🐙 autogpt
(.venv) rakumar7@L4W31Q34M2 AutoGPT % 
(.venv) rakumar7@L4W31Q34M2 AutoGPT % poetry run python cli.py setup     

       d8888          888             .d8888b.  8888888b. 88888888888 
      d88888          888            d88P  Y88b 888   Y88b    888     
     d88P888          888            888    888 888    888    888     
    d88P 888 888  888 888888 .d88b.  888        888   d88P    888     
   d88P  888 888  888 888   d88""88b 888  88888 8888888P"     888     
  d88P   888 888  888 888   888  888 888    888 888           888     
 d8888888888 Y88b 888 Y88b. Y88..88P Y88b  d88P 888           888     
d88P     888  "Y88888  "Y888 "Y88P"   "Y8888P88 888           888     
                                                                                                                                       

🚀 Setup initiated...

(.venv) rakumar7@L4W31Q34M2 AutoGPT % poetry run python cli.py agent list
Available agents: 🤖
        🐙 benchmark
        🐙 newbot
        🐙 bugbounty
        🐙 autogpt
(.venv) rakumar7@L4W31Q34M2 AutoGPT % poetry run python cli.py agent start autogpt
⌛ Running setup for agent 'autogpt'...
Installing dependencies from lock file

Package operations: 253 installs, 0 updates, 0 removals

  - Installing wrapt (1.16.0)
  - Installing zipp (3.17.0)
  - Installing deprecated (1.2.14)
  - Installing idna (3.6)
  - Installing importlib-metadata (6.11.0)
  - Installing protobuf (4.25.2)
  - Installing pyasn1 (0.5.1)
  - Installing sniffio (1.3.0)
  - Installing anyio (4.2.0)
  - Installing attrs (23.2.0)
  - Installing cachetools (5.3.2)
  - Installing catalogue (2.0.10)
  - Installing certifi (2023.11.17)
  - Installing charset-normalizer (3.3.2)
  - Installing googleapis-common-protos (1.62.0)
  - Installing grpcio (1.60.0)
  - Installing h11 (0.14.0)
  - Installing opentelemetry-api (1.22.0)
  - Installing pyasn1-modules (0.3.0)
  - Installing rsa (4.9)
  - Installing setuptools (69.0.3)
  - Installing six (1.16.0)
  - Installing typing-extensions (4.9.0)
  - Installing urllib3 (1.26.18)
  - Installing asgiref (3.7.2)
  - Installing asttokens (2.4.1)
  - Installing backoff (2.2.1)
  - Installing cymem (2.0.8)
  - Installing executing (2.0.1)
  - Installing filelock (3.13.1)
  - Installing frozenlist (1.4.1)
  - Installing fsspec (2023.12.2)
  - Installing google-auth (2.26.2)
  - Installing grpcio-status (1.60.0)
  - Installing httpcore (0.17.3)
  - Installing humanfriendly (10.0)
  - Installing jmespath (1.0.1)
  - Installing mpmath (1.3.0)
  - Installing multidict (6.0.4): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  *********************
  * Accelerated build *
  *********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-14.0-arm64-cpython-312
  creating build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/_multidict_py.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/_abc.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/_multidict_base.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/_compat.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  adding license file 'LICENSE'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  /private/var/folders/sy/9plgwq3110l9yz7g2v97j3_80000gp/T/tmp4csy2_5n/.venv/lib/python3.12/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'multidict._multilib' is absent from the `packages` configuration.
  !!
  
          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'multidict._multilib' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.
  
          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'multidict._multilib' is explicitly added
          to the `packages` configuration field.
  
          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
  
          You can read more about "package discovery" on setuptools documentation page:
  
          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
  
          If you don't want 'multidict._multilib' to be distributed and are
          already explicitly excluding 'multidict._multilib' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.
  
          You can read more about "package data files" on setuptools documentation page:
  
          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
  
  
          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************
  
  !!
    check.warn(importable)
  copying multidict/__init__.pyi -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/py.typed -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  running build_ext
  building 'multidict._multidict' extension
  creating build/temp.macosx-14.0-arm64-cpython-312
  creating build/temp.macosx-14.0-arm64-cpython-312/multidict
  clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/sy/9plgwq3110l9yz7g2v97j3_80000gp/T/tmp4csy2_5n/.venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c multidict/_multidict.c -o build/temp.macosx-14.0-arm64-cpython-312/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  In file included from multidict/_multidict.c:9:
  multidict/_multilib/iter.h:225:20: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  multidict_iter_init()
                     ^
                      void
  In file included from multidict/_multidict.c:10:
  multidict/_multilib/views.h:388:21: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  multidict_views_init()
                      ^
                       void
  multidict/_multidict.c:458:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "getall", 0};
                                      ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  multidict/_multidict.c:458:43: warning: incompatible pointer types initializing 'const char *' with an expression of type 'const char *const[3]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "getall", 0};
                                            ^~~~~~~~~
  multidict/_multidict.c:458:54: warning: incompatible pointer types initializing 'const char *const *' with an expression of type 'char[7]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "getall", 0};
                                                       ^~~~~~~~
  multidict/_multidict.c:503:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "getone", 0};
                                      ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  multidict/_multidict.c:503:43: warning: incompatible pointer types initializing 'const char *' with an expression of type 'const char *const[3]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "getone", 0};
                                            ^~~~~~~~~
  multidict/_multidict.c:503:54: warning: incompatible pointer types initializing 'const char *const *' with an expression of type 'char[7]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "getone", 0};
                                                       ^~~~~~~~
  multidict/_multidict.c:538:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "get", 0};
                                      ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  multidict/_multidict.c:538:43: warning: incompatible pointer types initializing 'const char *' with an expression of type 'const char *const[3]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "get", 0};
                                            ^~~~~~~~~
  multidict/_multidict.c:538:54: warning: incompatible pointer types initializing 'const char *const *' with an expression of type 'char[4]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "get", 0};
                                                       ^~~~~
  multidict/_multidict.c:712:5: warning: 'UsingDeprecatedTrashcanMacro' is deprecated [-Wdeprecated-declarations]
      Py_TRASHCAN_SAFE_BEGIN(self);
      ^
  /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/object.h:551:9: note: expanded from macro 'Py_TRASHCAN_SAFE_BEGIN'
          UsingDeprecatedTrashcanMacro cond=1; \
          ^
  /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/object.h:548:1: note: 'UsingDeprecatedTrashcanMacro' has been explicitly marked deprecated here
  Py_DEPRECATED(3.11) typedef int UsingDeprecatedTrashcanMacro;
  ^
  /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/pyport.h:317:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  multidict/_multidict.c:780:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "add", 0};
                                      ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  multidict/_multidict.c:780:43: warning: incompatible pointer types initializing 'const char *' with an expression of type 'const char *const[3]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "add", 0};
                                            ^~~~~~~~~
  multidict/_multidict.c:780:54: warning: incompatible pointer types initializing 'const char *const *' with an expression of type 'char[4]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "add", 0};
                                                       ^~~~~
  multidict/_multidict.c:839:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "setdefault", 0};
                                      ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  multidict/_multidict.c:839:43: warning: incompatible pointer types initializing 'const char *' with an expression of type 'const char *const[3]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "setdefault", 0};
                                            ^~~~~~~~~
  multidict/_multidict.c:839:54: warning: incompatible pointer types initializing 'const char *const *' with an expression of type 'char[11]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "setdefault", 0};
                                                       ^~~~~~~~~~~~
  multidict/_multidict.c:875:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "popone", 0};
                                      ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  multidict/_multidict.c:875:43: warning: incompatible pointer types initializing 'const char *' with an expression of type 'const char *const[3]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "popone", 0};
                                            ^~~~~~~~~
  multidict/_multidict.c:875:54: warning: incompatible pointer types initializing 'const char *const *' with an expression of type 'char[7]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "popone", 0};
                                                       ^~~~~~~~
  multidict/_multidict.c:922:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "pop", 0};
                                      ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  multidict/_multidict.c:922:43: warning: incompatible pointer types initializing 'const char *' with an expression of type 'const char *const[3]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "pop", 0};
                                            ^~~~~~~~~
  multidict/_multidict.c:922:54: warning: incompatible pointer types initializing 'const char *const *' with an expression of type 'char[4]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "pop", 0};
                                                       ^~~~~
  multidict/_multidict.c:970:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "popall", 0};
                                      ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  multidict/_multidict.c:970:43: warning: incompatible pointer types initializing 'const char *' with an expression of type 'const char *const[3]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "popall", 0};
                                            ^~~~~~~~~
  multidict/_multidict.c:970:54: warning: incompatible pointer types initializing 'const char *const *' with an expression of type 'char[7]' [-Wincompatible-pointer-types]
      static _PyArg_Parser _parser = {NULL, _keywords, "popall", 0};
                                                       ^~~~~~~~
  multidict/_multidict.c:1684:18: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
  PyInit__multidict()
                   ^
                    void
  20 warnings and 8 errors generated.
  error: command '/Library/Developer/CommandLineTools/usr/bin/clang' failed with exit code 1
  

  at /opt/homebrew/Cellar/poetry/1.8.3_1/libexec/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with multidict (6.0.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "multidict (==6.0.4)"'.

  - Installing murmurhash (1.0.10)
  - Installing numpy (1.26.3)
  - Installing oauthlib (3.2.2)
  - Installing opentelemetry-instrumentation (0.43b0)
  - Installing opentelemetry-proto (1.22.0)
  - Installing opentelemetry-semantic-conventions (0.43b0)
  - Installing opentelemetry-util-http (0.43b0)
  - Installing outcome (1.3.0.post0)
  - Installing packaging (23.2)
  - Installing parso (0.8.3)
  - Installing ptyprocess (0.7.0)
  - Installing pure-eval (0.2.2)
  - Installing pycparser (2.21)
  - Installing pydantic (1.10.13)
  - Installing pyparsing (3.1.1)
  - Installing python-dateutil (2.8.2)
  - Installing pyyaml (6.0.1)
  - Installing requests (2.31.0)
  - Installing rpds-py (0.17.1)
  - Installing sortedcontainers (2.4.0)
  - Installing srsly (2.4.8)
  - Installing tqdm (4.66.1)
  - Installing traitlets (5.14.1)
  - Installing wcwidth (0.2.13)
Setup completed successfully.

⌛ (Re)starting benchmark server...
INFO:     Started server process [40950]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

⌛ (Re)starting agent 'autogpt'...
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Warning: 'serve' is an entry point defined in pyproject.toml, but it's not installed as a script. You may get improper `sys.argv[0]`.

The support to run uninstalled scripts will be removed in a future release.

Run `poetry install` to resolve and get rid of this message.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/rakumar7/Downloads/Downloads/autogpt/AutoGPT/autogpt/autogpt/app/__init__.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Traceback (most recent call last):
  File "/Users/rakumar7/Downloads/Downloads/autogpt/AutoGPT/cli.py", line 505, in <module>
    cli()
  File "/Users/rakumar7/Library/Caches/pypoetry/virtualenvs/autogpt-Y2PYc-k_-py3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rakumar7/Library/Caches/pypoetry/virtualenvs/autogpt-Y2PYc-k_-py3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/rakumar7/Library/Caches/pypoetry/virtualenvs/autogpt-Y2PYc-k_-py3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rakumar7/Library/Caches/pypoetry/virtualenvs/autogpt-Y2PYc-k_-py3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rakumar7/Library/Caches/pypoetry/virtualenvs/autogpt-Y2PYc-k_-py3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rakumar7/Library/Caches/pypoetry/virtualenvs/autogpt-Y2PYc-k_-py3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rakumar7/Downloads/Downloads/autogpt/AutoGPT/cli.py", line 159, in start
    wait_until_conn_ready(8000)
  File "/Users/rakumar7/Downloads/Downloads/autogpt/AutoGPT/cli.py", line 501, in wait_until_conn_ready
    raise TimeoutError(f"Port {port} did not open within {timeout} seconds")
TimeoutError: Port 8000 did not open within 30 seconds
(.venv) rakumar7@L4W31Q34M2 AutoGPT % 
(.venv) rakumar7@L4W31Q34M2 AutoGPT %

**Comment by melkins14** [comment]
agreed. this sucks now. and the regular open ai version does ALL THIS

**Comment by kcze** [comment]
Sorry for delay with replies.

@kittenvr as you figured out the issue seemed to be wrong line endings; [stackoverflow](https://stackoverflow.com/questions/14219092/bash-script-bin-bashm-bad-interpreter-no-such-file-or-directory)
Line endings should be `LF` (Unix), not `CRLF` (Windows). *Saving `cli.py` file on Windows may overwrite it to use `CRLF`*.
Your second issue looks related to `click` package, you can try using Python 3.11 and updating `click`.

@rakeshbitsindri Your issue was resolved on `master` around the time you posted your comment [commit](https://github.com/Significant-Gravitas/AutoGPT/commit/23dfdad454b5142773e5b9571bde85222e98b67b#diff-50997d0a38b1e338082b724342f48b3c32fae5b29a5391cbe7d7f9f0b1065dbcR59). `multidict` package was changed from version `6.0.4` to `6.0.5` and it should setup fine now.
