### ISSUE TITLE
Azure endpoint not configured

### ISSUE THREAD

**Issue by hello-word-1** [Significant-Gravitas/AutoGPT#7448]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4(32k)

### Which area covers your issue best?

Installation and setup

### Describe your issue.

<img width="437" alt="1721039481006" src="https://github.com/user-attachments/assets/63fc7888-bd9b-4561-8ff8-af4238110591">
![image](https://github.com/user-attachments/assets/24b3687d-af82-422b-a352-738f2613a4d2)
![image](https://github.com/user-attachments/assets/d99b8922-e95f-4059-bf60-c727e10f09c2)
![image](https://github.com/user-attachments/assets/30cb90f5-8024-4074-a85d-e0e3c7f48e5d)

### Upload Error Log Content

![image](https://github.com/user-attachments/assets/a7dcb56b-7a07-4293-8f8d-2e9c3cb27448)

**Comment by ShahrOZe69** [comment]
Same issue

**Comment by EldestBard** [comment]
Same, it seems like bug in forge.

**Comment by teq-baotran** [comment]
Same issue. (While debugging, I see that ./autgpt can read the .env and azure.yaml files, but ./forge is unable to load any values from them.)

**Comment by DevWand** [comment]
Same issue

**Comment by jahe-ui** [comment]
Hi, same issue for me.

Is there a release that is working with a self hosted azure GPT instance? The recommended way as described in https://docs.agpt.co/classic/setup/#openai does not seem to work, as seen in this issue.

Does the "non-classic" version of AutoGPT work? I ask since this issue is labeled as "Classic AutoGPT Agent".

Thank you very much for the help and all the work, it would be great to get this running with a self hosted azure GPT instance, as we cannot use openai due to privacy issues.

**Comment by ntindle** [comment]
Updating the nonclassic to use Azure would be easy for someone in the community to do, and it would be much appreciated. I am happy to get a PR into the platform (non-classics name), but I'm closing this for now as we don't plan on continuing work on classic
